// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_rMQdaC1FLec5zTbCvMbdCdpG4S3LNm8',
    appId: '1:72159179870:web:138ea33db358ace0aeb0cf',
    messagingSenderId: '72159179870',
    projectId: 'beautystudio-63af9',
    authDomain: 'beautystudio-63af9.firebaseapp.com',
    storageBucket: 'beautystudio-63af9.firebasestorage.app',
    measurementId: 'G-4FSDDEW303',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZPFxlk4Pp785KIEeUE9t_eDsagthIAI',
    appId: '1:72159179870:android:338425a4b11d58acaeb0cf',
    messagingSenderId: '72159179870',
    projectId: 'beautystudio-63af9',
    storageBucket: 'beautystudio-63af9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLIzOFCd4ExKpSdUMqjPutV5RYP3S5idM',
    appId: '1:72159179870:ios:d985c45cff7bc879aeb0cf',
    messagingSenderId: '72159179870',
    projectId: 'beautystudio-63af9',
    storageBucket: 'beautystudio-63af9.firebasestorage.app',
    iosBundleId: 'com.example.beautystudio',
  );
}
